# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 915311985a20d906592bffb57ffc8ee11b12c576082d3ab0e2d528568db18dfadedbaa6b95b7995cb042b119f94f93d378af3bd31bc3ab642cb8ac6fc4192323

test:
  secret_key_base: d040e24ccaf32d1b6e32b0723345f0e4e0be5e31c27d9499d0e040123cfe701c11311531cc42bb7824ab98f5e1793101667f407bcd23afc07fd6865d75b9968b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
